// import {
//   Grid2X2,
//   Truck,
//   MapPin,
//   ShoppingCart,
//   Asterisk,
//   Landmark,
// } from "lucide-react";

// export const menuItems = {
//   navMain: [
//     {
//       title: "Dashboard",
//       url: "/",
//       icon: Grid2X2,
//       isActive: false,
//       isExpandable: false,
//       matchNested: true,
//     },
//     {
//       title: "Managers",
//       url: "/managers",
//       icon: Truck,
//       isActive: false,
//       isExpandable: false,
//       matchNested: true,
//     },
//     {
//       title: "Courts",
//       url: "/courts",
//       icon: MapPin,
//       isActive: false,
//       isExpandable: false,
//       matchNested: true,
//     },
//     {
//       title: "Orders",
//       url: "/orders/list-view",
//       icon: ShoppingCart,
//       isActive: false,
//       isExpandable: false,
//       matchNested: true,
//     },
//     {
//       title: "My brand",
//       url: "/mybrand",
//       icon: Asterisk,
//       isActive: false,
//       isExpandable: false,
//     },
//     {
//       title: "Banking",
//       url: "/banking",
//       icon: Landmark,
//       isActive: false,
//       isExpandable: false,
//     },
//     {
//       title: "Offer",
//       url: "/offer",
//       icon: Landmark,
//       isActive: false,
//       isExpandable: false,
//     },
//     {
//       title: "Payment History",
//       url: "/payment",
//       icon: Landmark,
//       isActive: false,
//       isExpandable: false,
//     },
//   ],
// };

import {
  Grid2X2,
  Map,
  Building2,
  ShoppingCart,
  CircleDollarSign,
  Layers3,
  DollarSign,
  Users,
  Percent,
  Tags,
  List,
  Landmark,
} from "lucide-react";

export const menuItems = {
  navMain: [
    {
      title: "Dashboard",
      url: "/",
      icon: Grid2X2,
      isActive: false,
      isExpandable: false,
      matchNested: true,
    },
    {
      title: "Organisation",
      url: "/organisation",
      icon: Building2,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "Venues",
      url: "/venues",
      icon: Map,
      isActive: false,
      isExpandable: false,
      matchNested: true,
    },
    {
      title: "Court",
      icon: Layers3,
      isExpandable: true,
      items: [
        {
          title: "Court",
          url: "/court",
          icon: Layers3,
          payloadCollection: "court",
          permissionSkip: true,
        },
        {
          title: "Court Availability",
          url: "/availability",
          payloadCollection: "courtAvailability",
          permissionSkip: true,
        },
        {
          title: "Court Price",
          url: "/court-price",
          icon: DollarSign,
          payloadCollection: "courtPrice",
          permissionSkip: true,
        },
      ],
    },
    //come in setting page
    // {
    //   title: "My brand",
    //   url: "/brand",
    //   icon: Palette,
    //   isActive: false,
    //   isExpandable: false,
    // },
    // {
    //   title: "Manager",
    //   url: "/manager",
    //   icon: BadgeCheck,
    //   isActive: false,
    //   isExpandable: false,
    // },
    {
      title: "Orders",
      url: "/orders",
      icon: ShoppingCart,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "Payment History",
      url: "/payments",
      icon: CircleDollarSign,
      isActive: false,
      isExpandable: false,
    },
    // come in setting page
    // {
    //   title: "Banking",
    //   url: "/banking",
    //   icon: Landmark,
    //   isActive: false,
    //   isExpandable: false,
    // },
    {
      title: "Customers",
      icon: Users,
      isExpandable: true,
      items: [
        {
          title: "List",
          url: "/customers/customers",
          icon: List,
          payloadCollection: "customers",
          permissionSkip: true,
        },
        {
          title: "Groups",
          url: "/customers/groups",
          icon: Users,
          payloadCollection: "customerGroups",
          permissionSkip: true,
        },
      ],
    },
    {
      title: "Promotion",
      url: "/promotion",
      icon: Percent,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "Offer",
      url: "/offer",
      icon: Landmark,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "Price List",
      url: "/price-list",
      icon: Tags,
      isActive: false,
      isExpandable: false,
    },
  ],
};
