import {
  Grid2X2,
  ChartPie,
  BadgeCheck,
  Tag,
  ThumbsUp,
  Truck,
  Map,
  MapPin,
  ShoppingCart,
  CircleDollarSign,
  Asterisk,
  Factory,
  Landmark,
} from "lucide-react";

export const menuItems = {
  navMain: [
    {
      title: "Dashboard",
      url: "/",
      icon: Grid2X2,
      isActive: false,
      isExpandable: false,
      matchNested: true,
    },
    {
      title: "Tire suppliers",
      url: "/tire-suppliers",
      icon: ChartPie,
      isActive: false,
      isExpandable: false,
      matchNested: true,
    },
    {
      title: "Tire Brands",
      url: "/tire-brands",
      icon: BadgeCheck,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "Tire pricing ",
      url: "/tire-pricing",
      icon: Tag,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "Tire recommendations ",
      url: "#",
      icon: ThumbsUp,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "Vans/Techs",
      icon: Truck,
      isActive: false,
      isExpandable: true,
      items: [
        {
          title: "Vans",
          url: "/vans-techs/vans",
          payloadCollection: "vans",
        },
        {
          title: "Managers",
          url: "/vans-techs/technicians",
          payloadCollection: "technicians",
        },
      ],
    },
    {
      title: "Territories & availability",
      url: "#",
      icon: Map,
      isActive: false,
      isExpandable: true,
      permissionSkip: true,
      items: [
        {
          title: "Hours of operation",
          url: "/territories-availability/hours-of-operation",
          permissionSkip: true,
        },
      ],
    },
    {
      title: "Courts",
      url: "/courts",
      icon: MapPin,
      isActive: false,
      isExpandable: false,
      matchNested: true,
    },
    {
      title: "Orders",
      url: "#",
      icon: ShoppingCart,
      isActive: false,
      isExpandable: true,
      permissionSkip: true,
      items: [
        {
          title: "List view",
          url: "/orders/list-view",
          permissionSkip: true,
        },
        {
          title: "Calendar view",
          url: "/orders/calendar-view",
          permissionSkip: true,
        },
        {
          title: "Map view",
          url: "/orders/map-view",
          permissionSkip: true,
        },
        {
          title: "Route view",
          url: "/orders/route-view",
          permissionSkip: true,
        },
      ],
    },
    {
      title: "Service pricing",
      icon: CircleDollarSign,
      isActive: false,
      isExpandable: true,
      permissionSkip: true,
      items: [
        {
          title: "Trip charge",
          url: "/service-pricing/trip-charge",
          permissionSkip: true,
        },
        {
          title: "Install",
          url: "/service-pricing/install",
          permissionSkip: true,
        },
        {
          title: "Patch repair",
          url: "/service-pricing/patch-repair",
          permissionSkip: true,
        },
        {
          title: "Balance & rotation",
          url: "/service-pricing/balance-rotation",
          permissionSkip: true,
        },
        {
          title: "Fees",
          url: "/service-pricing/fees",
          permissionSkip: true,
        },
      ],
    },
    {
      title: "My brand",
      url: "/mybrand",
      icon: Asterisk,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "My warehouse",
      url: "/dashboard",
      icon: Factory,
      isActive: false,
      isExpandable: false,
    },
    {
      title: "Banking",
      url: "/banking",
      icon: Landmark,
      isActive: false,
      isExpandable: false,
    },
     {
      title: "Offer",
      url: "/offer",
      icon: Landmark,
      isActive: false,
      isExpandable: false,
    },
  ],
};
